CREATE TABLE CAMINHAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    RENAVAM CHAR(11) NOT NULL UNIQUE,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    LICENCIAMENTO YEAR NOT NULL,
    AETS VARCHAR(100),
    DHINC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);